name: twonly
description: "twonly, a privacy-friendly way to connect with friends through secure, spontaneous image sharing."

publish_to: 'none'

version: 0.0.71+71

environment:
  sdk: ^3.6.0

dependencies:
  archive: ^4.0.7
  audio_waveforms: ^1.3.0
  avatar_maker: ^0.4.0
  background_downloader: ^9.2.2
  cached_network_image: ^3.4.1
  camera: ^0.11.2
  collection: ^1.18.0
  connectivity_plus: ^7.0.0
  cryptography_flutter_plus: ^2.3.4
  cryptography_plus: ^2.7.0
  device_info_plus: ^12.1.0
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  emoji_picker_flutter: ^4.3.0
  ffmpeg_kit_flutter_new: ^4.1.0
  file_picker: ^10.3.6
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  flutter_android_volume_keydown: ^1.0.1
  flutter_image_compress: ^2.4.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: a06ead81809c900e7fc421a30db0adf3b5919139 # from develop
      path: flutter_secure_storage/
  flutter_svg: ^2.0.17
  flutter_volume_controller: ^1.3.4
  flutter_zxing:
    path: ./dependencies/flutter_zxing
  font_awesome_flutter: ^10.10.0
  gal: ^2.3.1
  get: ^4.7.2
  hand_signature: ^3.0.3
  hashlib: ^2.0.0
  http: ^1.3.0
  image: ^4.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  libsignal_protocol_dart: ^0.7.4
  local_auth: ^3.0.0
  logging: ^1.3.0
  lottie: ^3.3.1
  mutex: ^3.1.0
  no_screenshot: ^0.3.1
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  protobuf: ^4.0.0
  provider: ^6.1.2
  restart_app: ^1.3.2
  screenshot: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^9.8.0
  share_plus: ^12.0.0
  tutorial_coach_mark: ^1.3.0
  url_launcher: ^6.3.1
  vector_graphics: ^1.1.19
  video_player: ^2.9.5
  web_socket_channel: ^3.0.1

dependency_overrides: 
  camera_android_camerax: 
    # path: ../flutter-packages/packages/camera/camera_android_camerax
    git:
      url: https://github.com/otsmr/flutter-packages.git
      path: packages/camera/camera_android_camerax 
      ref: aef58af205a5f3ce6588a5c59bb2e734aab943f0
  flutter_android_volume_keydown:
    git:
      url: https://github.com/yenchieh/flutter_android_volume_keydown.git
      branch: fix/lStar-not-found-error
  flutter_secure_storage_darwin:
    git:
      url: https://github.com/juliansteenbakker/flutter_secure_storage.git
      ref: a06ead81809c900e7fc421a30db0adf3b5919139 # from develop
      path: flutter_secure_storage_darwin/
  # hardcoding the mirror mode of the VideCapture to MIRROR_MODE_ON_FRONT_ONLY

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_monochrome: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FF57CC99"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animated_icons/
    - assets/animations/
    - assets/passwords/
    - CHANGELOG.md

