name: twonly
description: "twonly, a privacy-friendly way to connect with friends through secure, spontaneous image sharing."

publish_to: 'none'

version: 0.0.96+96

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Trusted published dart.dev or tools.dart.dev
  collection: ^1.18.0
  fixnum: ^1.1.1
  meta: ^1.17.0
  http: ^1.3.0
  intl: ^0.20.2
  path: ^1.9.0
  logging: ^1.3.0
  web_socket_channel: ^3.0.1
  convert: ^3.1.2
  crypto: ^3.0.7
  clock: ^1.1.2
  html: ^0.15.6

  
  # Trusted publisher flutter.dev 
  camera: ^0.11.2
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  local_auth: ^3.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  vector_graphics: ^1.1.19
  video_player: ^2.10.1
  in_app_purchase: ^3.2.3
  go_router: ^17.1.0


  # Trusted publisher fluttercommunity.dev
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.1.0
  font_awesome_flutter: ^10.10.0
  share_plus: ^12.0.0
  package_info_plus: ^9.0.0


  # Trustworthy publishers
  firebase_core: ^4.3.0 # firebase.google.com
  firebase_messaging: ^16.1.0  # firebase.google.com
  json_annotation: ^4.9.0 # google.dev
  protobuf: ^4.0.0 # google.dev
  scrollable_positioned_list: ^0.3.8 # google.dev


  # Flutter Favorite 
  provider: ^6.1.2
  drift: ^2.25.1
  drift_flutter: ^0.2.4
  flutter_local_notifications: ^19.1.0
  sentry_flutter: ^9.8.0


  # With high download
  app_links: ^7.0.0 # 1.6 mio
  image: ^4.3.0 # 3.3 mio
  archive: ^4.0.7 # 6.5 mio
  file_picker: ^10.3.6 # 2 mio
  get: ^4.7.2 # 740 k
  flutter_secure_storage: ^10.0.0 # 1.85 mio
  permission_handler: ^12.0.0+1 # 2 mio


  # Not yet checked 
  audio_waveforms: ^2.0.0
  avatar_maker: ^0.4.0
  background_downloader: ^9.4.0
  cached_network_image: ^3.4.1
  cryptography_flutter_plus: ^2.3.4
  cryptography_plus: ^2.7.0
  flutter_android_volume_keydown: ^1.0.1
  flutter_image_compress: ^2.4.0
  flutter_volume_controller: ^1.3.4
  gal: ^2.3.1
  google_mlkit_barcode_scanning: ^0.14.1

  # flutter_secure_storage:
  #   git:
  #     url: https://github.com/juliansteenbakker/flutter_secure_storage.git
  #     ref: a06ead81809c900e7fc421a30db0adf3b5919139 # from develop
  #     path: flutter_secure_storage/


  # Overwritten by self-controlled repository
  emoji_picker_flutter: ^4.3.0

  # Packages which got overwritten using the twonly-app-dependencies repository
  restart_app: ^1.3.2
  photo_view: ^0.15.0
  hashlib: ^2.0.0
  libsignal_protocol_dart: ^0.7.4
  lottie: ^3.3.1
  mutex: ^3.1.0
  introduction_screen: ^4.0.0
  qr_flutter: ^4.1.0
  hand_signature: ^3.0.3
  flutter_sharing_intent: ^2.0.4
  no_screenshot: ^0.3.1
  google_mlkit_face_detection: ^0.13.1
  pro_video_editor: ^1.6.1
  video_compress: ^3.1.4

dependency_overrides:
  dots_indicator:
    path: ./dependencies/dots_indicator
  hashlib:
    path: ./dependencies/hashlib
  introduction_screen:
    path: ./dependencies/introduction_screen
  libsignal_protocol_dart:
    path: ./dependencies/libsignal_protocol_dart
  flutter_sharing_intent:
    path: ./dependencies/flutter_sharing_intent
  lottie:
    path: ./dependencies/lottie
  mutex:
    path: ./dependencies/mutex
  photo_view:
    path: ./dependencies/photo_view
  qr:
    path: ./dependencies/qr
  adaptive_number:
    path: ./dependencies/adaptive_number
  ed25519_edwards:
    path: ./dependencies/ed25519_edwards
  hand_signature:
    path: ./dependencies/hand_signature
  hashlib_codecs:
    path: ./dependencies/hashlib_codecs
  optional:
    path: ./dependencies/optional
  pointycastle:
    path: ./dependencies/pointycastle
  x25519:
    path: ./dependencies/x25519
  qr_flutter:
    path: ./dependencies/qr_flutter
  no_screenshot:
    path: ./dependencies/no_screenshot
  camera_android_camerax: 
    # path: ../flutter-packages/packages/camera/camera_android_camerax
    git:
      url: https://github.com/otsmr/flutter-packages.git
      path: packages/camera/camera_android_camerax 
      ref: 43b87faec960306f98d767253b9bf2cee61be630
  emoji_picker_flutter:
    # Fixes the issue with recent emojis (solved by https://github.com/Fintasys/emoji_picker_flutter/pull/238)
    # Using override until this gets merged.
    git:
      url: https://github.com/otsmr/emoji_picker_flutter.git
  flutter_android_volume_keydown:
    git:
      url: https://github.com/yenchieh/flutter_android_volume_keydown.git
      branch: fix/lStar-not-found-error
  # flutter_secure_storage_darwin:
  #   git:
  #     url: https://github.com/juliansteenbakker/flutter_secure_storage.git
  #     ref: a06ead81809c900e7fc421a30db0adf3b5919139 # from develop
  #     path: flutter_secure_storage_darwin/
  # hardcoding the mirror mode of the VideCapture to MIRROR_MODE_ON_FRONT_ONLY

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0
  in_app_purchase_platform_interface: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_monochrome: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FF57CC99"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/animated_icons/
    - assets/animations/
    - assets/passwords/
    - assets/filters/
    - CHANGELOG.md

